// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | AlliumsSlice
  | UtaArtistSpaceSlice
  | OrchidsSlice
  | OfrendaSlice
  | ThreePhotoCollageSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | DetailHeadingNextSlice
  | PrevNextSlice
  | ImageTextSlice
  | ContactSlice
  | AboutHeroSlice
  | DetailSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Footer Background Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_background_image: prismic.ImageField<never>;

  /**
   * Footer Form Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_form_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_form_label: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Item in *AboutHero → Default → Primary → Employee*
 */
export interface AboutHeroSliceDefaultPrimaryEmployeeItem {
  /**
   * Employee Photo field in *AboutHero → Default → Primary → Employee*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.employee[].employee_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  employee_photo: prismic.ImageField<never>;

  /**
   * Employee Name field in *AboutHero → Default → Primary → Employee*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.employee[].employee_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  employee_name: prismic.RichTextField;

  /**
   * Employee Bio field in *AboutHero → Default → Primary → Employee*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.employee[].employee_bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  employee_bio: prismic.RichTextField;
}

/**
 * Primary content in *AboutHero → Default → Primary*
 */
export interface AboutHeroSliceDefaultPrimary {
  /**
   * Bio field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Button Text field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Client List Heading field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.client_list_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client_list_heading: prismic.RichTextField;

  /**
   * Client List 1 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.client_list_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client_list_1: prismic.RichTextField;

  /**
   * Client List 2 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.client_list_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client_list_2: prismic.RichTextField;

  /**
   * Background Image field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Mobile Background Image field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.mobile_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_background_image: prismic.ImageField<never>;

  /**
   * Employee field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.employee[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  employee: prismic.GroupField<
    Simplify<AboutHeroSliceDefaultPrimaryEmployeeItem>
  >;
}

/**
 * Default variation for AboutHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHero*
 */
type AboutHeroSliceVariation = AboutHeroSliceDefault;

/**
 * AboutHero Shared Slice
 *
 * - **API ID**: `about_hero`
 * - **Description**: AboutHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroSlice = prismic.SharedSlice<
  "about_hero",
  AboutHeroSliceVariation
>;

/**
 * Primary content in *Alliums → Default → Primary*
 */
export interface AlliumsSliceDefaultPrimary {
  /**
   * Title Label field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_label: prismic.KeyTextField;

  /**
   * Title Link field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  title_link: prismic.LinkField;

  /**
   * Project Description field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;

  /**
   * Button Text field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image 1 field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Alliums → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alliums.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Default variation for Alliums Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlliumsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlliumsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Alliums*
 */
type AlliumsSliceVariation = AlliumsSliceDefault;

/**
 * Alliums Shared Slice
 *
 * - **API ID**: `alliums`
 * - **Description**: Alliums
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlliumsSlice = prismic.SharedSlice<
  "alliums",
  AlliumsSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Contact Page Text field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_page_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_page_text: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Detail → Default → Primary*
 */
export interface DetailSliceDefaultPrimary {
  /**
   * Paragraph 1 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.paragraph_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_1: prismic.RichTextField;

  /**
   * Paragraph 2 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.paragraph_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_2: prismic.RichTextField;

  /**
   * Video field in *Detail → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Image 1 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Image 5 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * Image 6 field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.image_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_6: prismic.ImageField<never>;
}

/**
 * Default variation for Detail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Detail*
 */
type DetailSliceVariation = DetailSliceDefault;

/**
 * Detail Shared Slice
 *
 * - **API ID**: `detail`
 * - **Description**: Detail
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailSlice = prismic.SharedSlice<"detail", DetailSliceVariation>;

/**
 * Primary content in *DetailHeadingNext → Default → Primary*
 */
export interface DetailHeadingNextSliceDefaultPrimary {
  /**
   * Heading field in *DetailHeadingNext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_heading_next.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Next Project Title field in *DetailHeadingNext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_heading_next.default.primary.next_project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  next_project_title: prismic.KeyTextField;

  /**
   * Next Project Link field in *DetailHeadingNext → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: detail_heading_next.default.primary.next_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  next_project_link: prismic.LinkField;
}

/**
 * Default variation for DetailHeadingNext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailHeadingNextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetailHeadingNextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DetailHeadingNext*
 */
type DetailHeadingNextSliceVariation = DetailHeadingNextSliceDefault;

/**
 * DetailHeadingNext Shared Slice
 *
 * - **API ID**: `detail_heading_next`
 * - **Description**: DetailHeadingNext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetailHeadingNextSlice = prismic.SharedSlice<
  "detail_heading_next",
  DetailHeadingNextSliceVariation
>;

/**
 * Item in *Hero → Dark → Primary → Links*
 */
export interface HeroSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *Hero → Dark → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Hero → Dark → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Dark → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Dark → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Dark → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Mobile Background Image field in *Hero → Dark → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.mobile_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_background_image: prismic.ImageField<never>;

  /**
   * Links field in *Hero → Dark → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryLinksItem>>;
}

/**
 * Dark variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Light → Primary*
 */
export interface HeroSliceLightPrimary {
  /**
   * Heading field in *Hero → Light → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.light.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Video field in *Hero → Light → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.light.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Background Image field in *Hero → Light → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.light.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Light variation for Hero Slice
 *
 * - **API ID**: `light`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceLight = prismic.SharedSliceVariation<
  "light",
  Simplify<HeroSliceLightPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceLight;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageText → Default → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * Heading field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Paragraph field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageText → TextLeft → Primary*
 */
export interface ImageTextSliceTextLeftPrimary {
  /**
   * Heading field in *ImageText → TextLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.textLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Paragraph field in *ImageText → TextLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.textLeft.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ImageText → TextLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.textLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TextLeft variation for ImageText Slice
 *
 * - **API ID**: `textLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSliceTextLeft = prismic.SharedSliceVariation<
  "textLeft",
  Simplify<ImageTextSliceTextLeftPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation = ImageTextSliceDefault | ImageTextSliceTextLeft;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Primary content in *Ofrenda → Default → Primary*
 */
export interface OfrendaSliceDefaultPrimary {
  /**
   * Image 1 field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Title Label field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_label: prismic.KeyTextField;

  /**
   * Title Link field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  title_link: prismic.LinkField;

  /**
   * Project Description field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;

  /**
   * Button Text field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image 2 field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Ofrenda → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ofrenda.default.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;
}

/**
 * Default variation for Ofrenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OfrendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OfrendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Ofrenda*
 */
type OfrendaSliceVariation = OfrendaSliceDefault;

/**
 * Ofrenda Shared Slice
 *
 * - **API ID**: `ofrenda`
 * - **Description**: Ofrenda
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OfrendaSlice = prismic.SharedSlice<
  "ofrenda",
  OfrendaSliceVariation
>;

/**
 * Primary content in *Orchids → Default → Primary*
 */
export interface OrchidsSliceDefaultPrimary {
  /**
   * Title Label field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_label: prismic.KeyTextField;

  /**
   * Title Link field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  title_link: prismic.LinkField;

  /**
   * Project Description field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;

  /**
   * Button Text field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Background Image field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Mobile Background Image field in *Orchids → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orchids.default.primary.mobile_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Orchids Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrchidsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OrchidsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Orchids*
 */
type OrchidsSliceVariation = OrchidsSliceDefault;

/**
 * Orchids Shared Slice
 *
 * - **API ID**: `orchids`
 * - **Description**: Orchids
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrchidsSlice = prismic.SharedSlice<
  "orchids",
  OrchidsSliceVariation
>;

/**
 * Primary content in *PrevNext → Default → Primary*
 */
export interface PrevNextSliceDefaultPrimary {
  /**
   * Previous Project Title field in *PrevNext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prev_next.default.primary.previous_project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  previous_project_title: prismic.KeyTextField;

  /**
   * Previous Project Link field in *PrevNext → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: prev_next.default.primary.previous_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  previous_project_link: prismic.LinkField;

  /**
   * Next Project Title field in *PrevNext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: prev_next.default.primary.next_project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  next_project_title: prismic.KeyTextField;

  /**
   * Next Project Link field in *PrevNext → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: prev_next.default.primary.next_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  next_project_link: prismic.LinkField;
}

/**
 * Default variation for PrevNext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrevNextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrevNextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrevNext*
 */
type PrevNextSliceVariation = PrevNextSliceDefault;

/**
 * PrevNext Shared Slice
 *
 * - **API ID**: `prev_next`
 * - **Description**: PrevNext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrevNextSlice = prismic.SharedSlice<
  "prev_next",
  PrevNextSliceVariation
>;

/**
 * Item in *SoCal → Default → Primary → Title Link*
 */
export interface ThreePhotoCollageSliceDefaultPrimaryTitleLinkItem {
  /**
   * Link field in *SoCal → Default → Primary → Title Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.title_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *SoCal → Default → Primary → Title Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.title_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *SoCal → Default → Primary*
 */
export interface ThreePhotoCollageSliceDefaultPrimary {
  /**
   * Video field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Title Link field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.title_link[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title_link: prismic.GroupField<
    Simplify<ThreePhotoCollageSliceDefaultPrimaryTitleLinkItem>
  >;

  /**
   * Project Description field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.project_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField;

  /**
   * Button Text field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Photo 1 field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.photo_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_1: prismic.ImageField<never>;

  /**
   * Photo 2 field in *SoCal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: three_photo_collage.default.primary.photo_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_2: prismic.ImageField<never>;
}

/**
 * Default variation for SoCal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreePhotoCollageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThreePhotoCollageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SoCal*
 */
type ThreePhotoCollageSliceVariation = ThreePhotoCollageSliceDefault;

/**
 * SoCal Shared Slice
 *
 * - **API ID**: `three_photo_collage`
 * - **Description**: ThreePhotoCollage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreePhotoCollageSlice = prismic.SharedSlice<
  "three_photo_collage",
  ThreePhotoCollageSliceVariation
>;

/**
 * Primary content in *UtaArtistSpace → Default → Primary*
 */
export interface UtaArtistSpaceSliceDefaultPrimary {
  /**
   * Title Label field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_label: prismic.KeyTextField;

  /**
   * Title Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  title_link: prismic.LinkField;

  /**
   * Title Description field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.title_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_description: prismic.RichTextField;

  /**
   * Button Text field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image 1 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Project 1 Title Label field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_1_title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_1_title_label: prismic.KeyTextField;

  /**
   * Project 1 Title Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_1_title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_1_title_link: prismic.LinkField;

  /**
   * Project 1 Description field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_1_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_1_description: prismic.RichTextField;

  /**
   * Image 3 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;

  /**
   * Project 2 Title Label field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_2_title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_2_title_label: prismic.KeyTextField;

  /**
   * Project 2 Title Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_2_title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_2_title_link: prismic.LinkField;

  /**
   * Project 2 Description field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_2_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_2_description: prismic.RichTextField;

  /**
   * Image 5 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_5: prismic.ImageField<never>;

  /**
   * Project 3 Title Label field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_3_title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_3_title_label: prismic.KeyTextField;

  /**
   * Project 3 Title Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_3_title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_3_title_link: prismic.LinkField;

  /**
   * Project 3 Description field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_3_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_3_description: prismic.RichTextField;

  /**
   * Image 6 field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.image_6
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_6: prismic.ImageField<never>;

  /**
   * Project 4 Title Label field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_4_title_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_4_title_label: prismic.KeyTextField;

  /**
   * Project 4 Title Link field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_4_title_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_4_title_link: prismic.LinkField;

  /**
   * Project 4 Description field in *UtaArtistSpace → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: uta_artist_space.default.primary.project_4_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_4_description: prismic.RichTextField;
}

/**
 * Default variation for UtaArtistSpace Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UtaArtistSpaceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UtaArtistSpaceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *UtaArtistSpace*
 */
type UtaArtistSpaceSliceVariation = UtaArtistSpaceSliceDefault;

/**
 * UtaArtistSpace Shared Slice
 *
 * - **API ID**: `uta_artist_space`
 * - **Description**: UtaArtistSpace
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UtaArtistSpaceSlice = prismic.SharedSlice<
  "uta_artist_space",
  UtaArtistSpaceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutHeroSlice,
      AboutHeroSliceDefaultPrimaryEmployeeItem,
      AboutHeroSliceDefaultPrimary,
      AboutHeroSliceVariation,
      AboutHeroSliceDefault,
      AlliumsSlice,
      AlliumsSliceDefaultPrimary,
      AlliumsSliceVariation,
      AlliumsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      DetailSlice,
      DetailSliceDefaultPrimary,
      DetailSliceVariation,
      DetailSliceDefault,
      DetailHeadingNextSlice,
      DetailHeadingNextSliceDefaultPrimary,
      DetailHeadingNextSliceVariation,
      DetailHeadingNextSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryLinksItem,
      HeroSliceDefaultPrimary,
      HeroSliceLightPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceLight,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceTextLeftPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      ImageTextSliceTextLeft,
      OfrendaSlice,
      OfrendaSliceDefaultPrimary,
      OfrendaSliceVariation,
      OfrendaSliceDefault,
      OrchidsSlice,
      OrchidsSliceDefaultPrimary,
      OrchidsSliceVariation,
      OrchidsSliceDefault,
      PrevNextSlice,
      PrevNextSliceDefaultPrimary,
      PrevNextSliceVariation,
      PrevNextSliceDefault,
      ThreePhotoCollageSlice,
      ThreePhotoCollageSliceDefaultPrimaryTitleLinkItem,
      ThreePhotoCollageSliceDefaultPrimary,
      ThreePhotoCollageSliceVariation,
      ThreePhotoCollageSliceDefault,
      UtaArtistSpaceSlice,
      UtaArtistSpaceSliceDefaultPrimary,
      UtaArtistSpaceSliceVariation,
      UtaArtistSpaceSliceDefault,
    };
  }
}
