import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
  display: "swap",
});

/* IF YOU NEED A SECOND FONT, PUT IT HERE:
const jost = Jost({
  subsets: ['latin'],
  variable: '--font-jost',
  display: 'swap',
}) */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(jost.variable, jost.variable)}>
      <body>{children}</body>
    </html>
  );
}
