// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./AboutHero")),
  alliums: dynamic(() => import("./Alliums")),
  contact: dynamic(() => import("./Contact")),
  detail: dynamic(() => import("./Detail")),
  detail_heading_next: dynamic(() => import("./DetailHeadingNext")),
  hero: dynamic(() => import("./Hero")),
  image_text: dynamic(() => import("./ImageText")),
  jh_piego: dynamic(() => import("./JhPiego")),
  ofrenda: dynamic(() => import("./Ofrenda")),
  orchids: dynamic(() => import("./Orchids")),
  pinata: dynamic(() => import("./Pinata")),
  portals: dynamic(() => import("./Portals")),
  prev_next: dynamic(() => import("./PrevNext")),
  three_photo_collage: dynamic(() => import("./SoCal")),
  uta_artist_space: dynamic(() => import("./UtaArtistSpace")),
};
