// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./AboutHero")),
  contact: dynamic(() => import("./Contact")),
  detail: dynamic(() => import("./Detail")),
  hero: dynamic(() => import("./Hero")),
  ofrenda: dynamic(() => import("./Ofrenda")),
  three_photo_collage: dynamic(() => import("./SoCal")),
};
